CREATE TABLE MAP (
  lock CHAR(1) NOT NULL DEFAULT 'X',
  width INT NOT NULL,
  height INT NOT NULL,
  image VARCHAR(2048) NOT NULL,

  CONSTRAINT PK_MAP PRIMARY KEY (lock),
  CONSTRAINT CK_MAP_Locked CHECK (lock = 'X')
);

CREATE TABLE MAP_BOUNDARY (
  id SERIAL PRIMARY KEY,
  path PATH NOT NULL
);

CREATE TABLE USER_PROFILE (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  x INT NOT NULL,
  y INT NOT NULL
);

CREATE TABLE USER_SESSION (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES USER_PROFILE (id) NOT NULL,
  session CHAR(36) NOT NULL,
  date_created timestamp default current_timestamp
);
